/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js}'],
  plugins: [require('@tailwindcss/typography')],
  theme: {
    extend: {
      colors: {
        'primary':                   '#adc6ff',
        'on-primary':                '#002e69',
        'primary-container':         '#4d8efe',
        'secondary':                 '#dab9ff',
        'secondary-container':       '#5a3287',
        'on-secondary-container':    '#cda2ff',
        'tertiary':                  '#ffb2b6',
        'tertiary-container':        '#e26c77',
        'error':                     '#ffb4ab',
        'background':                '#11131a',
        'surface':                   '#11131a',
        'surface-dim':               '#11131a',
        'surface-bright':            '#373941',
        'surface-container-lowest':  '#0c0e15',
        'surface-container-low':     '#191b23',
        'surface-container':         '#1d1f27',
        'surface-container-high':    '#282a31',
        'surface-container-highest': '#33343c',
        'on-surface':                '#e2e2ec',
        'on-surface-variant':        '#c2c6d5',
        'outline':                   '#8c909f',
        'outline-variant':           '#424753',
        'inverse-surface':           '#e2e2ec',
        'inverse-on-surface':        '#2e3038',
        'surface-variant':           '#33343c',
      },
      fontFamily: {
        'body':    ['Geist', 'sans-serif'],
        'code':    ['"JetBrains Mono"', 'monospace'],
        'display': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'display-lg':  ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg':     ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md':    ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'code-sm':     ['13px', { lineHeight: '20px', fontWeight: '400' }],
      },
      spacing: {
        'xs':  '4px',
        'sm':  '8px',
        'md':  '16px',
        'lg':  '24px',
        'xl':  '40px',
        '2xl': '64px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
    },
  },
}
